### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by keunhong** [keunhong/photoshape#1]
## Material Classifier
- [ ] Document synthetic data generation.
- [ ] Document LMDB dataset creation.
- [ ] Make classifier code less dependent on specific diretory structure.
